[package]
name = "dashboard"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.8.0"


[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-gcc"

[build-depencies]
slint-build = "1.8.0"
