import { Button, VerticalBox, Spinner, ProgressIndicator } from "std-widgets.slint";

export component Dashboard inherits Window {
    // width: 1920px;
    // height: 1080px;
    full-screen: true;
    

    // Speedometer gauge with speed text inside
    HorizontalLayout {
        spacing: 0px;
        height: 100%;
        width: 100%;
        Rectangle {
            width: 33%; height: 100%;
            VerticalLayout {
                Rectangle {
                    background: transparent;
                    
                    Text {
                        horizontal-alignment: center;
                        width: parent.width;
                        text: "Voltage: " + root.voltage + " V";
                        font-size: 48px;
                    }
                }

                VerticalBox {
                    x: 0px;
                    alignment: LayoutAlignment.stretch;
                    spacing: 10px;
                    Text { text: "BMS: " + root.tempBMS + " °C"; font-size: 48px; 
                        horizontal-alignment: TextHorizontalAlignment.center;}
                    Text { text: "Motor: " + root.tempMotor + " °C"; font-size: 48px; 
                        horizontal-alignment: TextHorizontalAlignment.center;}
                    Text { text: "Controller: " + root.tempController + " °C"; font-size: 48px; 
                        horizontal-alignment: TextHorizontalAlignment.center;}

                }
            }
        }
        Rectangle {
            width: 34%; height: 100%;
            VerticalLayout {
            height: 100%;
            horizontal-stretch: 1;
            spacing: 30px;

            Rectangle {
                width: 100%; height: 100%;
                background: transparent;

                // Left blinker (top left)
                Rectangle {
                    width: 50px; height: 50px;
                    x: 10px; y: 10px;
                    background: root.leftBlinkerOn ? #ffff00 : #808080;
                }

                // Right blinker (top right)
                Rectangle {
                    width: 50px; height: 50px;
                    x: parent.width - self.width - 10px; y: 10px;
                    background: root.rightBlinkerOn ? #ffff00 : #808080;
                }

                Text {
                text: root.speed + " mph";
                font-size: 144px;
                horizontal-alignment: center;
                vertical-alignment: center;
                width: parent.width;
                height: parent.height;
                }
            }

            HorizontalLayout {
                spacing: 20px;
                alignment: center;
                Rectangle {
                width: 50px; height: 50px;
                background: root.leftBlinkerOn ? #ffff00 : #808080;
                }   

                Rectangle {
                width: 50px; height: 50px;
                background: root.rightBlinkerOn ? #ffff00 : #808080;
                }
            }
            }
        }

        Rectangle {
            width: 33%; height: 100%;
            VerticalLayout {
                Rectangle {
                    background: transparent;
                    height: parent.height/2;
                    
                    Text {
                        horizontal-alignment: center;
                        width: parent.width;
                        height: parent.height;
                        vertical-alignment: bottom;
                        text: "Throttle: " + root.throttle + " %";
                        font-size: 36px;
                        y: 0px;
                    }
                }

                Rectangle {
                    width: 100%;
                    height: 40px;
                    Rectangle {
                        width: 400px; height: 40px;
                        background: #cccccc;
                        Rectangle {
                            width: parent.width * (root.throttle / 100);
                            height: parent.height;
                            background: #4caf50;
                        }
                        border-radius: 5px;
                        border-width: 1px;
                        clip: false;
                        border-color: #888888;
                    }
                }
            }
        }
    }

    

    
    

    // Exposed properties
    in property<float> speed;
    in property<float> voltage;
    in property<bool> leftBlinkerOn;
    in property<bool> rightBlinkerOn;
    in property<int> throttle;
    in property<int> tempBMS;
    in property<int> tempMotor;
    in property<int> tempController;
}
