import { Button, VerticalBox, Spinner, ProgressIndicator } from "std-widgets.slint";

export component Dashboard inherits Window {
    max-width: 1920px;
    max-height: 1080px;
    full-screen: true;

    HorizontalLayout {
        VerticalLayout {
            alignment: center;
            spacing: 10px;

            Text {
                text: "BMS: " + root.tempBMS + " °C";
                font-size: 20px;
                horizontal-alignment: TextHorizontalAlignment.center;
            }

            Text {
                text: "Motor: " + root.tempMotor + " °C";
                font-size: 20px;
                horizontal-alignment: TextHorizontalAlignment.center;
            }

            Text {
                text: "limitId: " + root.limitId;
                font-size: 20px;
                horizontal-alignment: TextHorizontalAlignment.center;
            }

            // Tempature readout for controller is broken rn
            // Text {
            //     text: "Controller: " + root.tempController + " °C";
            //     font-size: 20px;
            //     horizontal-alignment: TextHorizontalAlignment.center;
            // }

            Text {
                text: "Headlights: " + (root.headlightsOn ? "On" : "Off");
                font-size: 20px;
                color: root.headlightsOn ? blue : black;
                horizontal-alignment: TextHorizontalAlignment.center;
            }
        }

        VerticalLayout {
            alignment: center;
            padding: 50px;

            HorizontalLayout {
                alignment: space-between;

                Rectangle {
                    width: 50px;
                    height: 50px;
                    background: root.leftBlinkerOn ? #ffff00 : #808080;
                }

                Rectangle {
                    width: 50px;
                    height: 50px;
                    background: root.rightBlinkerOn ? #ffff00 : #808080;
                }
            }

            Text {
                text: root.speed;
                font-size: 144px;
                horizontal-alignment: center;
            }

            Text {
                text: "mph";
                font-size: 100px;
                horizontal-alignment: center;
            }

            Text {
                text: root.errorOut;
                font-size: 20px;
                color: #ff0000;
                horizontal-alignment: center;
            }

            for item in root.limitFlags: Text {
                text: "Limit: " + item;
                font-size: 20px;
                color: blue;
                horizontal-alignment: center;
            }
        }

        VerticalLayout {
            padding: 50px;
            alignment: center;

            Rectangle {
                width: 300px;
                height: 90px;
                Rectangle {
                    width: 400px;
                    height: 50px;
                    Text {
                        text: "Throttle: " + root.throttle + " %";
                        font-size: 35px;
                    }
                }

                Rectangle {
                    y: 70px;
                    width: 300px;
                    height: 40px;
                    background: #cccccc;
                    Rectangle {
                        width: parent.width * (root.throttle / 100);
                        height: parent.height;
                        background: #4caf50;
                    }

                    border-radius: 5px;
                    border-width: 1px;
                    clip: false;
                    border-color: #888888;
                }
            }
        }
    }

    in property <float> speed;
    in property <bool> leftBlinkerOn;
    in property <bool> rightBlinkerOn;
    in property <bool> headlightsOn;
    in property <int> throttle;
    in property <int> tempBMS;
    in property <int> limitId;
    in property <float> tempMotor;
    in property <string> errorOut;
    in property <[string]> limitFlags;
}
